### ISSUE TITLE
Windows Discovery crashes

### ISSUE THREAD

**Issue by fboulegue** [USBToolBox/tool#9]
Hey Hey, I ve run that on my Windows 10 SSD, but it simply crashes after discovery, I did run the discovery and it shows me for a few second 

###################################################
# Port Discovery #
#######################################################

After that I did try the debug version that's under release, this doesn't even show up.

Any idea?

**Comment by dhinakg** [comment]
Please open `cmd`, drag and drop `Windows.exe`, run it and Discover Ports, then send the output of the crashing.
As per debug_dump:
> A dump from `debug_dump.exe` (available from the releases tab). You can get this by opening `cmd`, `cd`ing to Downloads or wherever you downloaded it, and running `debug_dump.exe`. Then copy and paste all the output into Notepad and upload it somewhere. Or you could pipe it to a file: add ` > debug.txt` to the command, then upload `debug.txt`.

**Comment by fboulegue** [comment]
Ah that's how to run the debug thanks @dhinakg attached the debug + a new screenshot of the error

<img width="675" alt="Unbenannt" src="https://user-images.githubusercontent.com/2719590/117384139-99234700-aee2-11eb-802a-2e33ec9fc242.PNG">
[debug.txt](https://github.com/USBToolBox/tool/files/6438366/debug.txt)

**Comment by dhinakg** [comment]
Thanks for the report, this should be fixed in 0.0.8. Please check.

**Comment by aguys123** [comment]
I still have the same issue on 0.0.8

[noname.jpg](https://user-images.githubusercontent.com/83843623/117510854-613e0180-afbf-11eb-8483-f1bcdccc0373.jpg)

Debug file 
[debug.txt](https://github.com/USBToolBox/tool/files/6444423/debug.txt)

**Comment by fboulegue** [comment]
@dhinakg can confirm working kext is builded and all ports a guessed :-)! great work!

**Comment by dhinakg** [comment]
@fboulegue That's good! Closing this issue.

@aguys123 You have a different issue, I've opened a new issue: #12
